Add octokit GitHub enterprise plugin and remove octokit/graphql
github/ghec-audit-log-cli pull request #20
Opened 2021-04-07 14:40 UTC by froi

This PR adds options to export audit log data at the enterprise level.

2021-04-07 16:40 UTC, froi commented
I'm still working through the graphql changes. Hopefully I'll have something done today.

2021-04-07 19:09 UTC, froi commented
I think it's best if we limit the scope of this PR to API v3. The work to do for v4 might be more complex because of how we would need to handle pagination and cursors.

2021-04-08 09:02 UTC, droidpl requested changes
This is an amazing job!! Thanks for the contribution @froi 

Just a minor validation issue reported, the rest looks ✨  to me

2021-04-08 09:02 UTC, droidpl commented on ghec-audit-log-utils.js
> +      presence: false
Use the `inclusion` validation to make sure it contains either `org` or `enterprise`

2021-04-08 09:04 UTC, droidpl commented
I agree on your statement for V3 work. Moving forward that is what will work and graphql may be deprecated in the future. Quick question there, may make sense to add a validation error if the combination of api-type v4 with enterprise appear? This way we fail gracefully

2021-04-08 12:00 UTC, froi commented
Makes sense, I'll take a look at it today.

2021-04-12 19:01 UTC, froi commented
@droidpl I think this PR should be done at this point. I've added your observations and a bit extra in the README.

2021-04-13 10:17 UTC, droidpl approved these changes
LGTM! Lets merge it an generate a new release

2021-04-13 10:17 UTC, merged