Add `npm install` instruction at the _Running the CLI_ section
github/ghec-audit-log-cli pull request #26
Opened 2021-06-03 11:13 UTC by kyanny

Hi @droidpl 👋 

When I tried to use `ghec-audit-log-cli` first time, I got an error like this.

```
$ git clone https://github.com/github/ghec-audit-log-cli
$ cd ghec-audit-log-cli
$ node ghec-audit-log-cli -v
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'yaml'
Require stack:
- /ghec-audit-log-cli/ghec-audit-log-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ghec-audit-log-cli/ghec-audit-log-cli.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ghec-audit-log-cli/ghec-audit-log-cli.js' ]
}
```

That's because the node modules hadn't installed yet.

Because I am not familiar with Node.js ecosystem, I wasn't aware that I need to run `npm install` before executing the command.

Although the _Installing as CLI_ section mentions to run `npm link`, I think it's for the different purpose. So that I think it's worth adding `npm install` instruction to the _Running the CLI_ section.

This pull request adds `npm install` instruction to the _Running the CLI_ section of the `README.md`.

2021-06-03 11:35 UTC, droidpl requested changes
I've made a quick suggestion to avoid any confusion on what is the things that need to run. Adding the pre-requisites section may help people to realize better what they need to execute.

Thanks again for raising those improvements ✨

2021-06-03 11:35 UTC, droidpl commented on README.md
> +```
```suggestion
Execute the command using node or npm

### Pre-requisites

 Install the node dependencies:

```shell script
$ git clone https://github.com/github/ghec-audit-log-cli
$ cd ghec-audit-log-cli
$ npm install
```
```

2021-06-04 03:19 UTC, kyanny commented
Hi @droidpl I agree with you, I've applied your suggestion. Can you have a look again?

2021-06-04 08:25 UTC, droidpl approved these changes
Merging it @kyanny 🚢 !

2021-06-04 08:25 UTC, merged